[package]
name = "ellipticoin-test-framework"
version = "0.1.0"
authors = ["Mason Fischer <mason@kissr.co>"]
description = "A framework for testing Ellipticoin smart contracts"
license = "MIT"

[dependencies]
cask = "0.*"
wasm-rpc = "0.1.0"
ellipticoin = "0.1.0"
